version: '2'
services:
  demo-app:
    image: demo
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8084:8084

